### ISSUE TITLE
[BUG]: Screen getting cleared on changing pen stroke size / pen color / background color

### ISSUE THREAD

**Issue by Debatreya** [singodiyashubham87/Draw-it-out#2] opened 2024-03-25 20:01 UTC

**Comment by singodiyashubham87** [comment] 2024-03-26 04:32
@Debatreya Did you tried the app on mobile device or laptop?

**Comment by Debatreya** [comment] 2024-03-26 04:34
Laptop

**Comment by singodiyashubham87** [comment] 2024-03-27 19:55
@Debatreya Please attach a recording if possible as it's working fine on my device.
By the way, which OS are you using?

**Comment by Debatreya** [comment] 2024-03-27 19:56
Windows

**Comment by singodiyashubham87** [comment] 2024-03-29 05:25
@Debatreya I'll check it out, thanks for pointing it out.

**Comment by kumar1397** [comment] 2024-05-09 16:34
This issue might be occuring may be due to the canvas component getting re-rendered every time a setting is changed or due to the event handling code for changing pen stroke size, pen color, and background color.
Assign me this issue under GSSoC '24 so that I can check the error and work on it.

**Comment by The-Phoenics** [comment] 2024-05-10 14:38
Hi @singodiyashubham87,
It seems the bug is caused by calling `setState` on the thickness state variable in the App component, which triggers a re-render of the entire canvas, resulting in an empty state.

One possible solution could be to use a `drawHistory` array 
https://github.com/singodiyashubham87/Draw-it-out/blob/18353fbccd34703ac96f2893927017a576c9e8ba/src/utils/canvas.js#L2
where we store stroke data. After the canvas re-renders, we can repopulate it with strokes from the drawHistory array. This approach could also be useful if we want to implement an undo functionality in the future.

Could you please assign this issue to me? I'd like to work on it for GSSoC'2024, and we can discuss the details further.

**Comment by singodiyashubham87** [comment] 2024-05-10 17:10
@kumar1397 Proceed!

**Comment by siddxharth1** [comment] 2024-05-10 19:31
Hey @singodiyashubham87  i have resolved the issue of wiping the screen on pen stroke or pen color change. and additionally i have fixed some ui breaking bugs and added a custom canvas background color picker.
Could you assign me this issue  under gssoc 24 
![Screenshot 2024-05-11 005601](https://github.com/singodiyashubham87/Draw-it-out/assets/91618085/9553a28d-f454-47a3-88af-be4801e194a4)
This is a screenshot of the result I attempted to provide.

**Comment by AMISH-KHAN** [comment] 2024-05-14 19:45
hey @singodiyashubham87  can I work on this?

**Comment by kumar1397** [comment] 2024-05-15 01:40
> @kumar1397 Are you working on the issue?

As @AMISH-KHAN has resolved the issue, you can assign him this issue. I have noticed other issues in this project which I will raise and resolve.

**Comment by kumar1397** [comment] 2024-05-15 01:45
> @kumar1397 Are you working on the issue?

Yes,
I am working on this issue. please give me some time to push it.

**Comment by 0xabdulkhalid** [comment] 2024-05-15 08:11
Bug have been fixed, So I'm closing this issue.

**Closed by 0xabdulkhalid** 2024-05-15 08:11 UTC
Labels: bug, up for grabs, gssoc, level2
