### ISSUE TITLE
Eraser tool

### ISSUE THREAD

**Issue by aapJoysakoi** [singodiyashubham87/Draw-it-out#325] opened 2024-06-07 08:13 UTC
**Is your feature request related to a problem? Please describe.**
A button to clear the full canvas but what if I want to erase just a part of it?

**Describe the solution you'd like**
Add an eraser tool which will provide the user with an option to partially erase a part of the artwork.

**Comment by aapJoysakoi** [comment] 2024-06-07 08:14
please assign me this issue under SSOC.

**Comment by singodiyashubham87** [comment] 2024-06-07 16:59
Duplicate of #36

**Closed by singodiyashubham87** 2024-06-07 16:59 UTC
Labels: enhancement, up for grabs
