### ISSUE TITLE
[Bug]: The Website is not responsive

### ISSUE THREAD

**Issue by r7projects-shayan** [singodiyashubham87/Draw-it-out#345] opened 2024-06-09 05:36 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The website is not responsive at all for various devices and dimensions

### Expected behavior

All the sections including the sections must be fully responsive in all devices and dimensions

### Add ScreenShots

![Screenshot 2024-06-09 110407](https://github.com/singodiyashubham87/Draw-it-out/assets/167475552/8736ab80-1f8d-430c-948f-55ff2cf958aa)
![Screenshot 2024-06-09 110415](https://github.com/singodiyashubham87/Draw-it-out/assets/167475552/7b478cdb-b614-4dcf-a08a-e816236b0536)

### On which device are you experiencing this bug?

Android, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by r7projects-shayan** [comment] 2024-06-09 05:36
@singodiyashubham87 Kindly assign me this issue

**Comment by singodiyashubham87** [comment] 2024-06-09 11:18
@r7projects-shayan Duplicate of #152

**Closed by singodiyashubham87** 2024-06-09 11:18 UTC
Labels: bug
