### ISSUE TITLE
Real-time collaborative drawing 

### ISSUE THREAD

**Issue by samiksha001** [singodiyashubham87/Draw-it-out#256] opened 2024-06-01 16:42 UTC
Add a feature where multiple users can work on the same canva simultaneously.

**Comment by samiksha001** [comment] 2024-06-01 16:45
Please assign this issue to me, i can add this feature which makes it even more user friendly.Thank you

**Comment by singodiyashubham87** [comment] 2024-06-05 19:54
Duplicate of #248

**Comment by singodiyashubham87** [comment] 2024-06-05 19:54
Duplicate of #248

**Closed** 2024-06-05 19:54 UTC
Labels: bug, up for grabs
