### ISSUE TITLE
[BUG] coffee item is not visible in dark mode

### ISSUE THREAD

**Issue by riffhi** [singodiyashubham87/Draw-it-out#323] opened 2024-06-07 06:38 UTC
**Describe the bug**
coffee icon isnt visible in dark mode

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/111896909/072b710c-282e-49e5-987c-3d63de58345b)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome

**Smartphone (please complete the following information):**
 - Device:oneplus
 - OS: android
 - Browser google

**Additional context**

**Comment by singodiyashubham87** [comment] 2024-06-07 16:58
Duplicate of #236

**Closed by singodiyashubham87** 2024-06-07 16:58 UTC
Labels: bug, up for grabs
