### ISSUE TITLE
[FEAT] Adding Responsive Footer section to the website

### ISSUE THREAD

**Issue by ujjwalagrawal-1** [singodiyashubham87/Draw-it-out#135] opened 2024-05-16 06:06 UTC
There is no Footer Section in the Website.

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/122930278/f5052c75-1ad8-49c3-9247-449635278ddc)

**Comment by singodiyashubham87** [comment] 2024-05-17 09:19
@ujjwalagrawal-1 Duplicate of #62

**Closed by singodiyashubham87** 2024-05-17 09:19 UTC
Labels: duplicate, enhancement, up for grabs
