### ISSUE TITLE
[FEAT] to add the feature of eraser 

### ISSUE THREAD

**Issue by suryapratapsingh26** [singodiyashubham87/Draw-it-out#233] opened 2024-05-29 18:43 UTC
**Is your feature request related to a problem? Please describe.**
eraser feature is required for this project as during drawing if user want to delete if any mistakes happened

**Comment by suryapratapsingh26** [comment] 2024-05-30 13:00
I am gssoc'24 participant i want to work on this feature . Assign me this

**Comment by singodiyashubham87** [comment] 2024-06-02 11:59
@suryapratapsingh26 Duplicate of #36

**Closed by singodiyashubham87** 2024-06-02 11:59 UTC
Labels: enhancement, up for grabs
