### ISSUE TITLE
[FEAT]: Adding an undo option in the application

### ISSUE THREAD

**Issue by mondalsurojit** [singodiyashubham87/Draw-it-out#288] opened 2024-06-03 04:26 UTC
**Is your feature request related to a problem? Please describe.**
To some extent. As when a user is drawing on the canvas, if something goes wrong, he/she can't correct it and the only left option is to "CLEAR" the whole canvas

**Describe the solution you'd like**
I would like to add an undo button, which when clicked wil take the user to the last change and discard the latest change

**Describe alternatives you've considered**
Adding an eraser option maybe. But both are different, with different purposes.

### Record

- [x] I agree to follow this project's Code of Conduct
- [x] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment] 2024-06-05 20:08
@mondalsurojit Duplicate of #32

**Closed by singodiyashubham87** 2024-06-05 20:08 UTC
Labels: enhancement, up for grabs
