### ISSUE TITLE
[FEAT] Missing DrawBot avatar

### ISSUE THREAD

**Issue by Harsh-KumarJha** [singodiyashubham87/Draw-it-out#238] opened 2024-05-30 14:28 UTC
**Is your feature request related to a problem? Please describe.**
No drawbot avatar is present in the chatbot.

**Describe the solution you'd like**
I can add a new draw bot avatar

**Describe alternatives you've considered**
A simple default placeholder bot avatar can also be added.

**Additional context**
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/121922047/0f635efd-ffc8-4c3e-af33-819b19b0e2fa)

I want to work on this issue under GSSoC. Kindly assign it to me.

**Comment by yasaswi-2204** [comment] 2024-05-30 16:10
I even felt that the drawbot avatar is not visible, I refreshed it again; but it is not visible to me.
Dear PA please assign me this issue under GSSOC, I will add a suitable and fantastic picture in the avatar.
I have expertise related to it.

**Comment by singodiyashubham87** [comment] 2024-06-02 12:03
Duplicate of #192

**Closed by singodiyashubham87** 2024-06-02 12:03 UTC
Labels: enhancement, up for grabs
