### ISSUE TITLE
[BUG] Canvas getting cleared after changing Brush size

### ISSUE THREAD

**Issue by khAja13** [singodiyashubham87/Draw-it-out#72] opened 2024-05-11 13:40 UTC
**Describe the bug**
After drawing something in the canvas, and if we try to change the brush size then all of the drawing are lost.

**To Reproduce**
1. Draw something on the canvas
2. Try increasing or decreasing the size of the brush.
3. See the canvas drawings getting cleared.

**Expected behavior**
The drawings should still be there and just the brush size should be changed.

**Comment by khAja13** [comment] 2024-05-11 13:41
Please do check and verify the changes I have made for the given bug.

**Comment by PranavN0509** [comment] 2024-05-11 19:58
@singodiyashubham87 I have successfully addressed the issue that resulted in the canvas clearing itself when changing the brush stroke size. I have submitted a pull request for the same. I would greatly appreciate it if you could consider my contribution for inclusion in GSSOC'24.

**Comment by singodiyashubham87** [comment] 2024-05-11 21:06
@khAja13 Duplicate of #2

**Closed by singodiyashubham87** 2024-05-11 21:06 UTC
Labels: bug, up for grabs
