### ISSUE TITLE
[FEAT] : Adding button to undo last action.

### ISSUE THREAD

**Issue by PranotiPD** [singodiyashubham87/Draw-it-out#159] opened 2024-05-18 10:24 UTC
**Is your feature request related to a problem? Please describe.**
There is no undo button to undo last drawn item.

**Describe the solution you'd like**
I would like to add button in given panel.

**Comment by singodiyashubham87** [comment] 2024-05-18 13:35
@PranotiPD Duplicate of #32

**Closed by singodiyashubham87** 2024-05-18 13:35 UTC
Labels: duplicate, enhancement, up for grabs
