### ISSUE TITLE
[BUG]: Chatbot avatar not visible in the website

### ISSUE THREAD

**Issue by arpy8** [singodiyashubham87/Draw-it-out#317] opened 2024-06-06 23:38 UTC
**Describe the bug**

The avatar in the website is not visible

**To Reproduce**
1. Go to 'the website'
2. Click on 'chatbot'
3. Notice the chatbot avatar

**Expected behavior**
The chatbot avatar should be visible

**Screenshots**

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/74809468/aca11567-f310-4930-b7c6-3042d06ffd26)

**Comment by singodiyashubham87** [comment] 2024-06-07 16:53
Duplicate of #192

**Closed by singodiyashubham87** 2024-06-07 16:53 UTC
Labels: bug, up for grabs
