### ISSUE TITLE
[BUG] Canvas height not increasing

### ISSUE THREAD

**Issue by iSubhamMani** [singodiyashubham87/Draw-it-out#243] opened 2024-05-31 15:53 UTC
**Describe the bug**

Canvas height fails to increase after being decreased below 10 pixels

**To Reproduce**
1. Go to Home Page
2. Decrease the canvas height below 10
3. Try to increase the height

**Expected behavior**
The canvas height should increase as expected when clicking on the + button even after the canvas height is below 10
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by iSubhamMani** [comment] 2024-05-31 15:54
@singodiyashubham87 I would like to work on this issue under SSOC'24. Please assign me this issue

**Comment by singodiyashubham87** [comment] 2024-06-02 10:11
@iSubhamMani Can you please add a recording of this?

**Comment by singodiyashubham87** [comment] 2024-06-02 12:07
@iSubhamMani I just checked & this issue was found to be a duplicate of #211 , So, I'm closing the issue.

**Closed by singodiyashubham87** 2024-06-02 12:07 UTC
Labels: bug, question, up for grabs, ssoc
