### ISSUE TITLE
[BUG]: Poor visibility of brush style section

### ISSUE THREAD

**Issue by kumar1397** [singodiyashubham87/Draw-it-out#217] opened 2024-05-27 14:55 UTC
**Describe the bug**
During the dark mode, the text color of the brush style button is whitish which results in poor visibility and it affects user experience.

**To Reproduce**
1. Go to 'the site'
2. Click on 'arrow button below the pen icon'
3. See error

**Expected behavior**
The text color could be black, improving the visibility of that section.

**Screenshots**
![Screenshot 2024-05-27 202101](https://github.com/singodiyashubham87/Draw-it-out/assets/122858524/5bbcf275-82e5-4c77-8546-0a16c8eff88b)

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser [Microsoft edge]

**Additional context**
Please assign this issue to me under GSSoC '24.

**Comment by singodiyashubham87** [comment] 2024-06-02 11:25
Duplicate of #189

**Closed by singodiyashubham87** 2024-06-02 11:25 UTC
Labels: bug, duplicate, up for grabs
