### ISSUE TITLE
add more background colors (custom color)

### ISSUE THREAD

**Issue by anshulsoni4** [singodiyashubham87/Draw-it-out#69] opened 2024-05-11 12:23 UTC
**Is your feature request related to a problem? Please describe.**
there are few colors 

**Describe the solution you'd like**
make more colors or use pick color from brush or custom 

**Describe alternatives you've considered**

**Additional context**

**Comment by singodiyashubham87** [comment] 2024-05-11 20:52
Do you want to work on the issue?

**Comment by singodiyashubham87** [comment] 2024-05-11 21:00
@anshulsoni4 I've assigned you the issue, Best of Luck!

**Comment by singodiyashubham87** [comment] 2024-05-11 21:05
Duplicate of #61

**Closed by singodiyashubham87** 2024-05-11 21:05 UTC
Labels: enhancement, up for grabs, gssoc, level1
