### ISSUE TITLE
NOT GOOD for mobile screen

### ISSUE THREAD

**Issue by Utsavladia** [singodiyashubham87/Draw-it-out#411] opened 2024-06-26 05:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The website is not resposive for the mobile screen which gives a very bad experiene to the users...

### Use Case

It shoud br uniformly designed for all devices to have a good user experience...

### Benefits

I would love to make it responsive for the mobile users and give a better experience..

### Add ScreenShots

![image](https://github.com/singodiyashubham87/Draw-it-out/assets/124615886/0de2fe77-4373-4963-b5ea-7fc2ae6224a3)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by 0xabdulkhalid** [comment] 2024-06-26 14:55
Hello @Utsavladia 👋🏻 

There's already several issues which are still working on to fix mobile responsiveness of Draw it out site. Since this issue is a duplicate of them so that i can't assign this issue to you.

You can create/work on any other new issue, Thank you!

**Closed by 0xabdulkhalid** 2024-06-26 14:55 UTC
Labels: enhancement
