### ISSUE TITLE
[FEAT]undo option not available

### ISSUE THREAD

**Issue by bishnudev35** [singodiyashubham87/Draw-it-out#247] opened 2024-06-01 07:44 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bishnudev35** [comment] 2024-06-01 07:45
i want  to work on the issue

**Comment by Vanicoding27** [comment] 2024-06-01 08:57
Please assign this task to me.

**Comment by singodiyashubham87** [comment] 2024-06-02 11:58
@bishnudev35 Duplicate of #32

**Closed by singodiyashubham87** 2024-06-02 11:58 UTC
Labels: enhancement, up for grabs
