### ISSUE TITLE
[FEAT] UNDO button integration

### ISSUE THREAD

**Issue by Atanu789** [singodiyashubham87/Draw-it-out#283] opened 2024-06-02 19:10 UTC
# Draw-it-Out Undo Button Missing

## Describe the feature
Currently, there is no undo button functionality implemented in the Draw-it-Out project. This means users cannot undo a drawing they've made, which can be frustrating if they make a mistake or want to backtrack on their actions.

## To Reproduce
1. Go to the Draw-it-Out website.
2. Start drawing something.
3. Make a mistake or decide to undo a part of the drawing.
4. Look for an undo button or option, which is currently missing.

## Expected behavior
The expected behavior is that users should have the ability to undo their drawing actions, through a dedicated undo button.

## Additional context
The absence of an undo button can significantly affect the user experience, especially for those who frequently use the drawing tool. Implementing this feature would enhance usability and make the tool more intuitive.

**Comment by Atanu789** [comment] 2024-06-02 19:11
hey @singodiyashubham87
kindly assign me the issue.

**Comment by singodiyashubham87** [comment] 2024-06-05 17:09
@Atanu789 Duplicate of #32

**Closed by singodiyashubham87** 2024-06-05 17:09 UTC
Labels: enhancement, up for grabs
