### ISSUE TITLE
[FEAT]  Add Collaborative Drawing Feature

### ISSUE THREAD

**Issue by Anushka-Pote** [singodiyashubham87/Draw-it-out#302] opened 2024-06-04 13:22 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't collaborate with others in real-time on the same drawing canvas. Currently, the Draw-it-out application only supports single-user drawing, which limits its usability for collaborative projects, educational purposes, and brainstorming sessions. This lack of real-time collaboration capabilities makes it challenging for multiple users to work together efficiently and effectively.

**Describe the solution you'd like**
I would like to see a collaborative drawing feature added to the Draw-it-out application, enabling multiple users to draw on the same canvas simultaneously. This feature should:
Allow users to join the same drawing session and see real-time updates to the canvas.
Provide a seamless and lag-free experience for all connected users.

**Describe alternatives you've considered**
Local Storage Sync: Implementing a local storage sync mechanism that periodically updates the canvas state across users. However, this approach might not provide the real-time experience necessary for smooth collaboration
Third-Party Collaborative Tools: Integrating third-party collaborative tools or platforms. This might be overkill for the scope of the Draw-it-out application and could complicate the user experience.

**Additional context**
Adding a collaborative feature will make the Draw-it-out application more versatile and appealing to a wider audience, including educators, designers, and teams looking for a simple yet effective collaborative drawing tool.

**Comment by singodiyashubham87** [comment] 2024-06-05 17:12
Duplicate of #256

**Closed by singodiyashubham87** 2024-06-05 17:12 UTC
Labels: enhancement, up for grabs
