### ISSUE TITLE
[FEAT]: Adding undo feature

### ISSUE THREAD

**Issue by Archiesachin** [singodiyashubham87/Draw-it-out#242] opened 2024-05-31 09:14 UTC
**Is your feature request related to a problem? Please describe.**
The whiteboard app has an clear the entire board feature. but to just undo the recent doodle there is no feature. 

**Describe the solution you'd like**
Adding a button on the top along with the shapes and pen option with the option of undo which will undo only the recent doodle on the whiteboard. 

**Additional context**
Assign  me this issue under GSSOC'24. Also add  the relevant labels.

**Comment by samiksha001** [comment] 2024-06-01 16:48
Please assign this issue to me,i can help add a undo and redo option for the users which makes it easier for them

**Comment by singodiyashubham87** [comment] 2024-06-02 12:06
@Archiesachin Duplicate of #32

**Closed by singodiyashubham87** 2024-06-02 12:06 UTC
Labels: enhancement, up for grabs
