### ISSUE TITLE
[Bug]: Content not clearly visible in dark mode

### ISSUE THREAD

**Issue by ankiiitagupta** [singodiyashubham87/Draw-it-out#415] opened 2024-06-27 17:12 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we turn dark mode on, some content of drop-down menu is not clearly visible.

### Expected behavior

I can fix this by changing the color of font so that it is visible.

### Add ScreenShots

![Screenshot 2024-06-27 223746](https://github.com/singodiyashubham87/Draw-it-out/assets/108889476/d7daab57-90b0-44e7-81d7-92a484d39230)
 

Please this issue to me under GSSOC,24.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment] 2024-06-28 03:30
Duplicate of #189

**Closed by singodiyashubham87** 2024-06-28 03:30 UTC
Labels: bug
