### ISSUE TITLE
[FEAT] Add Undo and Redo option 

### ISSUE THREAD

**Issue by Sayantan-Karmakar** [singodiyashubham87/Draw-it-out#311] opened 2024-06-06 07:49 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I make a mistake while drawing a line in the application and can't easily undo or redo the last action. This lack of functionality makes the drawing process less efficient and more time-consuming as I have to start over or manually correct mistakes.

https://github.com/singodiyashubham87/Draw-it-out/assets/103350515/6d663cc4-b730-4686-a4a5-e92b53664772

**Describe the solution you'd like**
I would like to have an undo and redo option available after drawing a line. This feature would store the drawing progress in memory, allowing users to quickly revert to previous states or redo actions as needed. This would enhance the usability of the drawing tool and make it more user-friendly.

**Describe alternatives you've considered**
An alternative solution could be implementing a history panel where users can see a list of all their actions and selectively revert to any previous state. Another option might be to add a confirmation prompt before finalizing a line to prevent mistakes, though this could slow down the drawing process.

**Additional context**
Implementing an undo/redo feature would significantly improve the user experience, especially for tasks that require precision and frequent adjustments. This feature is crucial for maintaining a smooth workflow and ensuring that users can easily correct any errors. 

This feature request is being submitted under GSSoC'24 (GirlScript Summer of Code 2024)

**Comment by Gokilp** [comment] 2024-06-06 14:06
please assign to me

**Comment by singodiyashubham87** [comment] 2024-06-07 16:49
Duplicate of #32

**Closed by singodiyashubham87** 2024-06-07 16:49 UTC
Labels: enhancement, up for grabs
