### ISSUE TITLE
[FEAT]: To select a functionality using a button click

### ISSUE THREAD

**Issue by a-khushal** [singodiyashubham87/Draw-it-out#49] opened 2024-05-10 16:59 UTC
To select a functionality using a button click
example: click 8 to draw

**Comment by a-khushal** [comment] 2024-05-10 16:59
@singodiyashubham87 can I work on this?

**Comment by thatsyogeshjjr** [comment] 2024-05-10 17:04
Duplicate of #36

**Comment by singodiyashubham87** [comment] 2024-05-10 17:12
@a-khushal I don't think there is a need of something like this, the buttons are enough to select specific tool.

**Comment by a-khushal** [comment] 2024-05-10 17:16
ok

**Closed** 2024-05-10 17:29 UTC
Labels: enhancement, up for grabs
