### ISSUE TITLE
Misaligned Guidelines w.r.t logo

### ISSUE THREAD

**Issue by Akash4701** [singodiyashubham87/Draw-it-out#250] opened 2024-06-01 11:46 UTC
**Describe the bug**
when i am clicking the top most logo, the guidelines are appearing in right side.

**To Reproduce**
1.Component Structure:
Ensure the dropdown button and the dropdown content are within the same parent container. This keeps their positioning relative to each other.

2.Tailwind CSS Classes:
Use Tailwind CSS classes to ensure proper alignment and positioning:
Apply relative to the parent container of the button and dropdown content.
Apply absolute left-0 to the dropdown content to align it directly under the button.

3.State Management in React:
Use React state to control the visibility of the dropdown content. This can be done using useState to toggle the dropdown's visibility when the button is clicked.

**Expected behavior**
The Guidelines should appear below the logo as expected.

**Comment by Akash4701** [comment] 2024-06-01 11:48
please assign me this issue #singodiyashubham87 for SSoC'2024

**Comment by singodiyashubham87** [comment] 2024-06-02 12:09
@Akash4701 Duplicate of #227

**Closed by singodiyashubham87** 2024-06-02 12:09 UTC
Labels: bug, up for grabs
