### ISSUE TITLE
[FEAT]adding an Undo button to revert back to the previous changes that was made 

### ISSUE THREAD

**Issue by AdhithiManjunath** [singodiyashubham87/Draw-it-out#145] opened 2024-05-17 10:06 UTC
**Is your feature request related to a problem? Please describe.**
generally if a person draws a sketch and makes slight mistake , the sketch has to be made again from d beginning

**Describe the solution you'd like**
best solution for this would be adding on eraser as a feature , or creating an undo button so that it can revert back to the previous change made 

**Describe alternatives you've considered**
eraser so that erase that part where changes are made 
we can even include redo button too

**Additional context**
please do allocate me this issue so that i can contribute to it . thank you !!

**Comment by singodiyashubham87** [comment] 2024-05-18 05:26
@AdhithiManjunath Duplicate of #32

**Closed by singodiyashubham87** 2024-05-18 05:26 UTC
Labels: duplicate, enhancement
