### ISSUE TITLE
Adding Undo button

### ISSUE THREAD

**Issue by sharmi4590** [singodiyashubham87/Draw-it-out#124] opened 2024-05-14 16:23 UTC
**Is your feature request related to a problem? Please describe.**
The user a does not always want to restart everything since on clicking cross button everything's erased , that's not a good user experience.

**Describe the solution you'd like**
I will create a Undo button and try to implement eraser also so that user can have his saved work history.

I am GSSoC'24 contributor.

**Comment by singodiyashubham87** [comment] 2024-05-14 19:17
@sharmi4590 Duplicate of #32

**Closed by singodiyashubham87** 2024-05-14 19:17 UTC
Labels: duplicate, enhancement, up for grabs
