### ISSUE TITLE
Add "Undo" Feature to the Drawing Application

### ISSUE THREAD

**Issue by avneeetk** [singodiyashubham87/Draw-it-out#183] opened 2024-05-21 12:44 UTC
**Is your feature request related to a problem? Please describe.**
Currently, the drawing application lacks an "Undo" feature. This makes it difficult for users to correct mistakes or revert changes, which can be frustrating and reduce the overall usability of the application.

**Describe the solution you'd like**
Maintain a History Stack: Introduce an array to store the history of canvas states.
Save State: Save the current state of the canvas to the history stack after each drawing action.
Implement Undo Functionality: Add an "Undo" button to the toolbar. When clicked, the button will revert the canvas to the last saved state.

please assign me this issue under gssoc'24

**Comment by singodiyashubham87** [comment] 2024-05-21 13:03
Duplicate of #32

**Closed by singodiyashubham87** 2024-05-21 13:03 UTC
Labels: enhancement, up for grabs
