### ISSUE TITLE
[FEAT]: Page is not responsive.

### ISSUE THREAD

**Issue by AMANVISHWAKARMA27** [singodiyashubham87/Draw-it-out#191] opened 2024-05-22 12:14 UTC
**Is your feature request related to a problem? Please describe.**
The website is not responsive at lower dimensions but can be made responsive
![image](https://github.com/singodiyashubham87/Draw-it-out/assets/143862235/5a45141b-bf8e-44a0-8199-aa63bbd48afe)

**Describe the solution you'd like**
It is possible to make it responsive for mobile dimensions also like canva or figma.

@singodiyashubham87 , kindly assign the issue to me.

**Comment by soumya-maheshwari** [comment] 2024-05-22 12:36
Hello @AMANVISHWAKARMA27 
This is a Duplicate of https://github.com/singodiyashubham87/Draw-it-out/issues/169

**Closed by soumya-maheshwari** 2024-05-22 12:36 UTC
Labels: enhancement, up for grabs
