### ISSUE TITLE
[Feature Request]: create a about us page

### ISSUE THREAD

**Issue by Prakrati1907** [singodiyashubham87/Draw-it-out#426] opened 2024-06-30 09:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

adding about us page , as mentioned in navbar
![Screenshot 2024-06-30 150706](https://github.com/singodiyashubham87/Draw-it-out/assets/120261907/6170b971-2b78-4ea9-b4bd-66030ae9d82f)
@singodiyashubham87 please assign this to me.

### Use Case

it will let people know more about this website and its features.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [ ] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment] 2024-07-01 10:49
@Prakrati1907 Duplicate of #226

**Closed by singodiyashubham87** 2024-07-01 10:49 UTC
Labels: enhancement
