### ISSUE TITLE
[FEAT]: Text color change is required

### ISSUE THREAD

**Issue by shreya-paul-17** [singodiyashubham87/Draw-it-out#316] opened 2024-06-06 16:31 UTC
**Is your feature request related to a problem? Please describe.**
The text color should be changed for better readability purpose 

**Describe the solution you'd like**
I would to change the font-color to black

**Describe alternatives you've considered**
N/A

**Additional context**
![draw-it-out](https://github.com/singodiyashubham87/Draw-it-out/assets/135226069/dc15d7b7-044d-42a7-ae63-cb825472d584)

I would like to work on this issue
I am a GSSoC 2024 contributor 
I agree to follow the contributing guidelines of the project
I agree to follow the Code of Conduct of the project

**Comment by singodiyashubham87** [comment] 2024-06-07 16:52
Duplicate of #189

**Closed by singodiyashubham87** 2024-06-07 16:52 UTC
Labels: enhancement, up for grabs
