### ISSUE TITLE
Undo/Redo Functionality 

### ISSUE THREAD

**Issue by sahil0414** [singodiyashubham87/Draw-it-out#297] opened 2024-06-04 02:57 UTC
**Is your feature request related to a problem? Please describe.**
Add undo and redo buttons to allow users to revert or reapply their last actions. This functionality is essential for correcting mistakes and experimenting with different drawing techniques.

**Describe the solution you'd like**
Feature Details:

Undo Button: Adds a button to the toolbar that allows users to undo their last action. When clicked, the most recent change to the drawing will be reverted.
Redo Button: Adds a button to the toolbar that allows users to redo an action that was undone. When clicked, the last undone action will be reapplied.
Action Stack: Implement a stack data structure to keep track of user actions. Each drawing action (e.g., strokes, shape additions, text insertions) will be pushed onto the stack. Undoing an action will pop it from the stack and move it to a redo stack. Redoing an action will push it back to the action stack.
Acceptance Criteria:

 Undo and redo buttons are added to the toolbar.
 Users can undo their last actions.
 Users can redo actions that were undone.
 A stack data structure is implemented to manage the history of actions for undo and redo functionality.

**Describe alternatives you've considered**

**Additional context**

Please assign me for this task

**Comment by singodiyashubham87** [comment] 2024-06-05 20:13
@sahil0414 Duplicate of #32

**Closed by singodiyashubham87** 2024-06-05 20:13 UTC
Labels: enhancement, up for grabs
