### ISSUE TITLE
Undo button

### ISSUE THREAD

**Issue by PuR-vI** [singodiyashubham87/Draw-it-out#167] opened 2024-05-19 18:43 UTC
I'd like to design and add an undo button which erases the last drawn line. It'd be great if you assign this issue to me under GSSOC'24

**Comment by soumya-maheshwari** [comment] 2024-05-19 21:10
@PuR-vI This is a Duplicate of https://github.com/singodiyashubham87/Draw-it-out/issues/32

**Closed** 2024-05-19 21:12 UTC
Labels: duplicate, enhancement, up for grabs
