### ISSUE TITLE
[BUG] contents gets erased when different colour is choosed

### ISSUE THREAD

**Issue by Harshitazz** [singodiyashubham87/Draw-it-out#82] opened 2024-05-12 06:43 UTC
**Describe the bug**
whwn different is picked from the pallette.all the contents get erased.

**To Reproduce**
1. draw on canvas 
2. go to color pallete
3. Click on different colour
5. See error

**Expected behavior**
all the content should remain 

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

@singodiyashubham87  assign it to me

**Comment by singodiyashubham87** [comment] 2024-05-12 17:41
@Harshitazz Duplicate of #2

**Comment by 0xabdulkhalid** [comment] 2024-05-14 03:49
Hi @Harshitazz 👋🏻, This Issue is a duplicate one. There's already an issue about fixing the bug.

So we can't assign you right now for this one. Since this is duplicate we're gonna close this one.

You can create new issue for contribution, Thank you!

**Closed by 0xabdulkhalid** 2024-05-14 03:49 UTC
Labels: bug, up for grabs
