### ISSUE TITLE
[FEAT] Add An Eraser

### ISSUE THREAD

**Issue by porwalshreyaa** [singodiyashubham87/Draw-it-out#119] opened 2024-05-14 09:15 UTC
**Problem**
A drawing app project is incomplete without an eraser.

**Solution**
Can create a button to select erasor feature. It'd be almost same as the brush except that you cannot choose color, erasor would use the color of the background by default, whatever it is.

**Alternative**
we could have used just the brush feature if the default bg color was in color selection pallate, another option is having the default color of canvas in pallate.

**context**
I think creating an eraser would look good but may make the web app slow, adding one more color in the pallate would be a better option. At the end of the day project admin has the right to decide this.

**Comment by porwalshreyaa** [comment] 2024-05-14 09:16
Assign this to me.

**Comment by singodiyashubham87** [comment] 2024-05-14 19:12
@porwalshreyaa Duplicate of #36.

**Comment by 0xabdulkhalid** [comment] 2024-05-15 05:18
Since this ISSUE is a duplicate, I'm closing this as not completed.

Please raise any new ISSUE for contribution,Thank you @porwalshreyaa!

**Closed by 0xabdulkhalid** 2024-05-15 05:18 UTC
Labels: duplicate, enhancement, up for grabs
