### ISSUE TITLE
[Bug]: the icon in chat button is not visible and also the alignment of gmail button is wrong

### ISSUE THREAD

**Issue by H1mang1** [singodiyashubham87/Draw-it-out#441] opened 2024-07-04 16:04 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the icon in chat section is not visible and the alignment of gmail button is wrong

### Expected behavior

the icon in chat section should be visible and the alignment of gmail button should be fixed 

### Add ScreenShots

![Screenshot 2024-07-04 212517](https://github.com/singodiyashubham87/Draw-it-out/assets/123282807/f9eb80cb-3c1b-4562-9f24-423380090702)
![Screenshot 2024-07-04 212450](https://github.com/singodiyashubham87/Draw-it-out/assets/123282807/0055eadb-132e-43d3-a63a-41c628d281cf)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment] 2024-07-05 16:34
Duplicate of #236

**Closed by singodiyashubham87** 2024-07-05 16:34 UTC
Labels: bug
