### ISSUE TITLE
[FEAT] Eraser Tool for Sketch Removal in Draw-it-out

### ISSUE THREAD

**Issue by Astha86** [singodiyashubham87/Draw-it-out#100] opened 2024-05-13 02:30 UTC
I've noticed that there seems to be one feature missing that could further enhance its usability.

I suggest the addition of an eraser tool to allow users to selectively erase sketches and drawings. This eraser tool would provide users with more control over their creations, enabling them to correct mistakes or refine their sketches with precision.

Implementing an eraser tool would not only improve the usability of Draw-it-out but also align with its goal of providing a comprehensive platform for creative expression and collaboration.

**Comment by Astha86** [comment] 2024-05-13 02:31
Hello, I'm interested in contributing to Draw-it-out's eraser tool for GSSOC'24. Please assign this issue to me.

**Comment by singodiyashubham87** [comment] 2024-05-13 12:23
@Astha86 Duplicate of #36

**Closed by singodiyashubham87** 2024-05-13 12:23 UTC
Labels: enhancement, up for grabs
