### ISSUE TITLE
Add Icons to Footer

### ISSUE THREAD

**Issue by sailaja-adapa** [singodiyashubham87/Draw-it-out#417] opened 2024-06-28 15:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

@singodiyashubham87   i would like add rate us on footer so when user click on that they will head to new page as i kept an screenshot before like that page will be appear in an attractive way according to our website still i didn't improved that much only i added rate us option on footer

![ico](https://github.com/singodiyashubham87/Draw-it-out/assets/161804629/0521aad1-62f4-4933-b89f-49430f7f4f5c)

### Use Case

It will make our Website to look Attractive

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I'm a SSOC'24 contributor
- [X] I want to work on this issue

**Comment by singodiyashubham87** [comment] 2024-06-29 18:49
Duplicate of #385

**Closed by singodiyashubham87** 2024-06-29 18:49 UTC
Labels: enhancement

**Comment by sailaja-adapa** [comment] 2024-07-01 12:39
Actually i thought i created a new issue but later i understood i raised it in #385 
Later i again raised another issue anyway no problem @singodiyashubham87
